export const moodTrackingQuestions = [
  {
    id: 1,
    question: "How would you rate your overall mood today?",
    type: "scale",
    scale: [1, 2, 3, 4, 5],
    labels: ["Very bad", "Bad", "Neutral", "Good", "Very good"],
  },
  {
    id: 2,
    question: "How much energy did you have throughout the day?",
    type: "scale",
    scale: [1, 2, 3, 4, 5],
    labels: ["None", "Low", "Moderate", "High", "Very high"],
  },
  {
    id: 3,
    question: "How well did you sleep last night?",
    type: "scale",
    scale: [1, 2, 3, 4, 5],
    labels: ["Very poor", "Poor", "Fair", "Good", "Excellent"],
  },
  {
    id: 4,
    question: "How stressed did you feel today?",
    type: "scale",
    scale: [1, 2, 3, 4, 5],
    labels: ["Not at all", "Slightly", "Moderately", "Very", "Extremely"],
  },
  {
    id: 5,
    question: "How socially connected did you feel today?",
    type: "scale",
    scale: [1, 2, 3, 4, 5],
    labels: [
      "Very isolated",
      "Somewhat isolated",
      "Neutral",
      "Connected",
      "Very connected",
    ],
  },
  {
    id: 6,
    question: "How motivated were you to complete daily tasks?",
    type: "scale",
    scale: [1, 2, 3, 4, 5],
    labels: ["Not at all", "Slightly", "Moderately", "Very", "Extremely"],
  },
  {
    id: 7,
    question: "How anxious did you feel today?",
    type: "scale",
    scale: [1, 2, 3, 4, 5],
    labels: ["Not at all", "Slightly", "Moderately", "Very", "Extremely"],
  },
  {
    id: 8,
    question: "How often did you experience negative thoughts today?",
    type: "scale",
    scale: [1, 2, 3, 4, 5],
    labels: ["Never", "Rarely", "Sometimes", "Often", "Always"],
  },
  {
    id: 9,
    question: "How satisfied are you with your personal relationships today?",
    type: "scale",
    scale: [1, 2, 3, 4, 5],
    labels: [
      "Not satisfied",
      "Slightly satisfied",
      "Neutral",
      "Satisfied",
      "Very satisfied",
    ],
  },
  {
    id: 10,
    question: "How hopeful do you feel about the future today?",
    type: "scale",
    scale: [1, 2, 3, 4, 5],
    labels: ["Not at all", "Slightly", "Moderately", "Very", "Extremely"],
  },
];
